config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount Sidekiq::Web in app
  mount Sidekiq::Web => "/sidekiq"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"

  # React UI
  get '/frontend' => 'frontend#index'

  get '/frontend/ruby' => 'frontend#ruby'

  resources :jobs
  
  # CRUD operations for Joke model
  resources :jokes do
    # nested resource, implies a hierarchical relationship / db association
    # CRUD operations for Comment model
    resources :comments
  end

  namespace :api do
    resources :jokes, :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :joke
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/joke.rb
class Joke < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy

  validates :author, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/api/comments_controller.rb
module Api
  class CommentsController < ApiController
    def index
      @comments = Comment.all

      render json: @comments, status: 200
    end

    def show
      @comment = Comment.find(params[:id])
      if @comment
        render json: @comment, status: 200
      else
        render json: { error: 'Error finding comment' }
      end
    end

    def create
      @joke = Joke.find(params[:joke_id])
      
      begin
        @comment = @joke.comments.create(comment_params)
        render json: @comment, status: 200
      rescue 
        render json: { error: "Error creating comment" }
      end
    end
  
    def update
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        render json: @joke, status: 200
      else
        render json: { error: 'Error updating comment' }
      end
    end

    def destroy
      @joke = Joke.find(params[:joke_id])
      @comment = @joke.comments.find(params[:id])

      begin 
        @comment.destroy!
        render json: null, status: 200
      rescue
        render json: { error: 'Error deleting comment' }
      end
    end
  
    private
      def comment_params
        params.require(:comment).permit(:author, :body, :status)
      end
  end
end

app/controllers/api/jokes_controller.rb
module Api
  class JokesController < ApiController
    def index
      @jokes = Joke.all
      render json: @jokes, status: 200
    end
  
    def show
      @joke = Joke.find(params[:id])

      if @joke
        render json: @joke, status: 200
      else
        render json: { error: 'Joke not found' }
      end
    end
  
    def create
      @joke = Joke.new(joke_params)

      if @joke.save
        render json: @joke, status: 200
      else
        render json: { error: 'Error creating joke' }
      end
    end
  
    def update
      @joke = Joke.find(params[:id])
      if @joke.update(joke_params)
        render json: @joke, status: 200
      else
        render json: { error: 'Error updating joke' }
      end
    end
  
    def destroy
      @joke = Joke.find(params[:id])
      if @joke.destroy
        render json: @joke, status: 200
      else
        render json: { error: 'Error deleting joke' }
      end
    end
  
    private
      def joke_params
        params.require(:joke).permit(:author, :title, :description, :status)
      end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :set_format

  def set_format
    request.format = :json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'indigov', password: 'indigov', only: :destroy
  
  def create
    @joke = Joke.find(params[:joke_id])
    @comment = @joke.comments.create(comment_params)

    redirect_to joke_path(@joke)
  end

  def destroy
    @joke = Joke.find(params[:joke_id])
    @comment = @joke.comments.find(params[:id])
    @comment.destroy

    redirect_to joke_path(@joke), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:author, :body, :status)
    end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  # React UI
  def index; end

  # Rails UI
  def ruby; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/jobs_controller.rb
require 'sidekiq/api'

class JobsController < ApplicationController
  def create
    HelloWorldJob.perform_later

    redirect_to jobs_path
  end

  def index
    @queues = Sidekiq::Queue.all
    puts @queues.to_json
    @queues 
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  http_basic_authenticate_with name: 'indigov', password: 'indigov', except: [:index, :show]

  def index
    @jokes = Joke.all
  end

  def show
    @joke = Joke.find(params[:id])
  end

  def new
    @joke = Joke.new
  end

  def create
    @joke = Joke.new(joke_params)

    if @joke.save
      redirect_to @joke
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @joke = Joke.find(params[:id])
  end

  def update
    @joke = Joke.find(params[:id])

    if @joke.update(joke_params)
      redirect_to @joke
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @joke = Joke.find(params[:id])
    @joke.destroy

    redirect_to jokes_path, status: :see_other
  end

  private
    def joke_params
      params.require(:joke).permit(:author, :title, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <%= comment.body %> - <i><%= comment.author %></i>
<% end %>

<p>
  <%= link_to "Destroy Comment", [comment.joke, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@joke, @joke.comments.build] do |form| %>
  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/frontend/index.html.erb
<!DOCTYPE html>                                                                      
<html> 
  <head>
    <title>Rails React Starter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'index.jsx' %>
  </head>

  <body>
    <div id="root" />
    <%= yield %>
  </body>
</html>

app/views/frontend/ruby.html.erb
<h1>Rails Application</h1>

<%= render "jobs/form" %>
<%= link_to "View jokes", jokes_path %>

app/views/home/index.html.erb
<h1>Welcome to React Rails!</h1>

<p class='text-red-300'>The React frontend is located under /app/frontend</p>
<p class='text-blue-300'>The Ruby frontend is located under /app/views</p>

app/views/jobs/_form.html.erb
<h1>Schedule Job</h1>

<%= form_with url: jobs_path do |f| %>
  <%= f.submit 'Launch Job' %>
<% end %>

app/views/jobs/_queues.html.erb
Queues
<ul>
  <% @queues.each do |queue| %>
    <li>
      <%= queue.name %>
    </li>
  <% end %>
</ul>

app/views/jobs/index.html.erb
<h1 class='text-3xl font-bold underline'>Jobs</h1>

<h2>Sidekiq Stats</h2>

<h3>Queues in flight</h3>
<%= render partial: "queues" %>

app/views/jokes/_form.html.erb
<%# all partials must be prefixed with _ %>
<%# during rendering, it is referenced without _ %>

<%= form_with model: joke do |form| %>
  <div>
    <%= form.label :author %>
    <br>
    <%= form.text_field :author %>
    <% joke.errors.full_messages_for(:author).each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_area :title %>
    <% joke.errors.full_messages_for(:title).each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
    <% joke.errors.full_messages_for(:description).each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
    <%= link_to "Cancel", jokes_path %>
  </div>
<% end %>

app/views/jokes/_joke.html.erb
<ul>
  <% @jokes.each do |joke| %>
    <% unless joke.archived? %>
      <li>
        <%= link_to joke.title, joke %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/jokes/edit.html.erb
<h1>Edit Joke</h1>

<%= render "form", joke: @joke %>

app/views/jokes/index.html.erb
<h1>Jokes</h1>

<p>We have <%= Joke.public_count %> inside jokes from our first dev on site!</p>

<%= render partial: "joke", collection: @jokes, as: :joke %>

<br>
<%= link_to "New Joke", new_joke_path %>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= render "form", joke: @joke %>

app/views/jokes/show.html.erb
<h1>
  <%= @joke.title %> 
</h1>
<p>
  <%= @joke.description %>
</p>
<p>
  - <%= @joke.author %>
</p>

<ul>
  <li>
    <%= link_to "Edit", edit_joke_path(@joke) %>
  </li>
  <li>
    <%= link_to "Delete", joke_path(@joke), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </li>
</ul>

<h3>Comments</h3>

<%# NOTE: is equivalent to render partial: "comments/comment", collection: @joke.comments, as: :comment %>
<%# render @joke.comments %>

<h6>Add comment</h6>
<%= render 'comments/form' %>

<%= link_to "Back to jokes", jokes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rails React Starter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= yield :head %>
  </head>

  <body>
    <div class='mx-20'>
      <a class='link' href='/'>Home</a>
      <a class='link' href='/frontend/ruby'>Ruby</a>
      <a class='link' href='/frontend'>React</a>
      <a class='link' href='/jobs'>Jobs</a>
      <%= yield %>
    </div>
  </body>
</html>